config/routes.rb
Rails.application.routes.draw do

  root "articles#index"

  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :excerpt, presence: true, length: {minimum:20, maximum:350}
    validates :body, presence: true, length: {minimum:600}
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true, length: {maximum:900}
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: 'nome1', password: 'senha1',
  except: [:index, :show]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new 
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit 
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private 
  def article_params
    params.require(:article).permit(:title, :excerpt, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: 'nome1', password: 'senha1',
    only: :destroy
  
    def create 
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = Comment.find(params[:id])
        @comment.destroy
    
        redirect_to article_path(@article)
      end
    
    private
    def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
    <%= form_with model: @article do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
        <% @article.errors.full_messages_for(:title).each do |message| %>
            <div class='error'><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :excerpt %>
        <%= form.text_area :excerpt, 'class' => 'excerpt' %>
        <% @article.errors.full_messages_for(:excerpt).each do |message| %>
            <div class='error'><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_area :body, 'class' => 'body' %>
        <% @article.errors.full_messages_for(:body).each do |message| %>
            <div class='error'><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :status %>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>
    <div class="submit-btn"><%= form.submit 'class' => 'contribute' %></div>

    <% end %>

app/views/articles/edit.html.erb
<h1 class="subpages-blog-title">
<%= link_to :root do %>
Might & Right
<% end %>
</h1>
<section class="new-container sub-w">
<h1>Edit Article</h1>
<%= render "form", article: @article %>
</section>

app/views/articles/index.html.erb
<div class="title-container">
<h1>Might & Right</h1>
<p>Woodland Stories</p>
</div>
<section class="articles-container home-w">
Our blog has <%= Article.public_count %> articles and counting!
<% @articles.each do |a| %>
    <% unless a.archived? %>
        <div class="article-preview">
            <h2><%= link_to article_path(id: a.id) do %><%= a.title %><% end %></h2>
            <p><%= a.excerpt %></p>
            <%= link_to "Read more...", article_path(id: a.id), 'class' => 'read-more' %>
        </div>
    <% end %>
<% end %>
</section>
<%= link_to new_article_path, 'class' => 'contribute fixed-btn' do %><i class="fa fa-plus"></i><% end %>

app/views/articles/new.html.erb
<h1 class="subpages-blog-title">
<%= link_to :root do %>
Might & Right
<% end %>
</h1>
<section class="new-container sub-w">
<h1>New Article</h1>
<%= render "form", article: @article %>
</section>

app/views/articles/show.html.erb
<h1 class="subpages-blog-title">
<%= link_to :root do %>
Might & Right
<% end %>
</h1>
<section class="article-container sub-w">
<h1><%= @article.title %></h1>
<div class='excerpt'><%= @article.excerpt %></div>
<hr>
<div class="body"><%= simple_format(@article.body) %></div>
<hr>
</section>
<section class="comments-container sub-w">
    <h2>Comments</h2>
    <%= render @article.comments %>
</section>
<section class="new-comment-container sub-w">
    <h2>Add a comment:</h2>
    <%= render 'comments/form' %>
</section>
<%= link_to article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, 'class' => 'delete fixed-btn' do %><i class="fa fa-trash"></i><%end%>
<%= link_to edit_article_path(id: @article.id), 'class' => 'edit fixed-btn' do %><i class="fa fa-edit"></i><% end %>

app/views/comments/_comment.html.erb
<p class='author'>
    @<%= comment.commenter %>:
</p>

<p class='comment'>
    <%= comment.body %>
</p>
<div class="w-100 p-end">
    <%= link_to "Delete", article_comment_path(id: comment.id, article_id: comment.article_id), method: :delete, data: {confirm: "Are you sure?"}, 'class' => 'delete del-comment' %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <div>
        <%= form.label :commenter %>
        <%= form.text_field :commenter %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>
    <div>
        <%= form.label :status %>
        <%= form.select :status, ['public', 'private'], selected: 'public' %>
    </div>
    <div class="submit-btn">
        <%= form.submit 'class' => 'contribute'  %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Might & Right</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("otter.png")%>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nova+Oval&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>